namespace: dev
replicaCount: 1
image:
  repository: praveenx03/printnow-user-service
  tag: v1.1.0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5001
  targetPort: 5001
config:
  PORT: "5001"
  NODE_ENV: development
  MONGO_URI: mongodb://mongodb-0.mongodb.dev.svc.cluster.local:27017/printnow
  USERS_COLLECTION: users
  JWT_EXPIRES_IN: 1d
secret:
  JWT_SECRET: dev-printnow-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_dev_printnow_user
  RAZORPAY_SECRET: dev-printnow-user-razorpay-secret
resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi


