worker_processes auto;
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {
    include mime.types;

    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        # 🔥 1. FILES (VERY IMPORTANT)
        location /uploads/ {
            proxy_pass http://document-service:5002/uploads/;
        }

        # 🔥 2. API ROUTES
        location /api/auth/ {
            proxy_pass http://user-service:5001/;
        }

        location /api/documents/ {
            proxy_pass http://document-service:5002/;
        }

        location /api/orders/ {
            proxy_pass http://order-service:5003/;
        }

        location /api/vendors/ {
            proxy_pass http://vendor-service:5004/;
        }

        # 🔥 3. REACT APP (MUST BE LAST)
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}