worker_processes auto;
pid /var/run/nginx.pid;
events { worker_connections 1024; }
http {
    include mime.types;
    server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        # Proxy pass API requests directly to container service names
        location /api/auth {
            proxy_pass http://user-service:5001;
        }
        location /api/documents {
            proxy_pass http://document-service:5002;
        }
        location /api/orders {
            proxy_pass http://order-service:5003;
        }
        location /api/vendors {
            proxy_pass http://vendor-service:5004;
        }
    }
}