apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: dev-printnow-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_test_SgxwwTh05ycq20
  RAZORPAY_SECRET: ib19bXnXUxULKn56i0kv7HsQ
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: prod-printnow-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_test_SgxwwTh05ycq20
  RAZORPAY_SECRET: ib19bXnXUxULKn56i0kv7HsQ


