version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: printnow-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - printnow-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/printnow
      - JWT_SECRET=supersecretjwtkey_printnow
    depends_on:
      - mongodb
    networks:
      - printnow-network

  document-service:
    build: ./document-service
    container_name: document-service
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongodb:27017/printnow
      - JWT_SECRET=supersecretjwtkey_printnow
    volumes:
      - document_uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - printnow-network

  order-service:
    build: ./order-service
    container_name: order-service
    restart: unless-stopped
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongodb:27017/printnow
      - JWT_SECRET=supersecretjwtkey_printnow
      - RAZORPAY_KEY_ID=rzp_test_SgxwwTh05ycq20
      - RAZORPAY_SECRET=ib19bXnXUxULKn56i0kv7HsQ
    depends_on:
      - mongodb
    networks:
      - printnow-network

  vendor-service:
    build: ./vendor-service
    container_name: vendor-service
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://mongodb:27017/printnow
      - JWT_SECRET=supersecretjwtkey_printnow
    depends_on:
      - mongodb
    networks:
      - printnow-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - document-service
      - order-service
      - vendor-service
    networks:
      - printnow-network

volumes:
  mongo_data:
  document_uploads:

networks:
  printnow-network:
    driver: bridge