apiVersion: v1
kind: Secret
metadata:
  name: document-service-secret
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: dev-document-service-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_dev_printnow_document
  RAZORPAY_SECRET: dev-printnow-document-razorpay-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: document-service-secret
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: prod-document-service-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_prod_printnow_document
  RAZORPAY_SECRET: prod-printnow-document-razorpay-secret
