apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
  RAZORPAY_KEY_ID: {{ .Values.secret.RAZORPAY_KEY_ID | quote }}
  RAZORPAY_SECRET: {{ .Values.secret.RAZORPAY_SECRET | quote }}


