apiVersion: v1
kind: Service
metadata:
  name: document-service
  labels:
    app: document-service
spec:
  selector:
    app: document-service
  ports:
    - port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  labels:
    app: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: praveenx03/printnow-document-service:v1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: printnow-config
          env:
            - name: PORT
              value: "5002"
            - name: RAZORPAY_KEY_ID
              value: "rzp_test_SgxwwTh05ycq20"
            - name: RAZORPAY_SECRET
              value: "ib19bXnXUxULKn56i0kv7HsQ"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          