apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: dev-printnow-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_dev_printnow_frontend
  RAZORPAY_SECRET: dev-printnow-frontend-razorpay-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: prod-printnow-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_prod_printnow_frontend
  RAZORPAY_SECRET: prod-printnow-frontend-razorpay-secret


