apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: dev-user-service-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_dev_printnow_user
  RAZORPAY_SECRET: dev-printnow-user-razorpay-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: prod
type: Opaque
stringData:
  JWT_SECRET: prod-user-service-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_prod_printnow_user
  RAZORPAY_SECRET: prod-printnow-user-razorpay-secret
