apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: dev
data:
  PORT: "5001"
  NODE_ENV: development
  MONGO_URI: mongodb://mongodb-0.mongodb.dev.svc.cluster.local:27017/printnow
  USERS_COLLECTION: users
  JWT_EXPIRES_IN: 1d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: prod
data:
  PORT: "5001"
  NODE_ENV: production
  MONGO_URI: mongodb://mongodb-0.mongodb.prod.svc.cluster.local:27017/printnow
  USERS_COLLECTION: users
  JWT_EXPIRES_IN: 12h

