namespace: prod
replicaCount: 2
image:
  repository: praveenx03/printnow-order-service
  tag: v1.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5003
  targetPort: 5003
config:
  PORT: "5003"
  NODE_ENV: production
  MONGO_URI: mongodb://mongodb-0.mongodb.prod.svc.cluster.local:27017/printnow
  ORDERS_COLLECTION: orders
  ORDER_TIMEOUT_MINUTES: "15"
secret:
  JWT_SECRET: prod-order-service-jwt-secret-2026
  RAZORPAY_KEY_ID: rzp_prod_printnow_order
  RAZORPAY_SECRET: prod-printnow-order-razorpay-secret
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi

